version: "3.9"

services:
  client:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - django_server
      - go_server

  django_server:
    build: ./django  # use Dockerfile to build custom image
    # TODO PART 1
    deploy:
      replicas: ${DJANGO_SERVER_REPLICAS}  # number of containers running for this service at any given time
      resources:
        limits:  # max amount of resources the service can use
          cpus: ${MAX_DJANGO_SERVER_CPU}
          memory: ${MAX_DJANGO_SERVER_MEMORY}
        reservations:  # guaranteed amount of resources for the service
          cpus: '0.2'
          memory: '256M'

  go_server:
    build: ./go
    # TODO PART 2
    deploy:
      replicas: ${GO_SERVER_REPLICAS}
      resources:
        limits:
          cpus: ${MAX_GO_SERVER_CPU}
          memory: ${MAX_GO_SERVER_MEMORY}
        reservations:
          cpus: '0.5'
          memory: '512M'

#DJANGO_SERVER_REPLICAS=3 GO_SERVER_REPLICAS=2 docker-compose up
